if ENV.fetch('GOOGLE_JSON', nil)
  GOOGLE_CREDENTIALS_PATH = 'tmp/google.json'.freeze
  File.write(GOOGLE_CREDENTIALS_PATH, ENV.fetch('GOOGLE_JSON', nil))
  ENV['GOOGLE_APPLICATION_CREDENTIALS'] = GOOGLE_CREDENTIALS_PATH
end
